// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/subcription/subcription.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdUser        int64                  `protobuf:"varint,2,opt,name=id_user,json=idUser,proto3" json:"id_user,omitempty"`
	IdCountry     int64                  `protobuf:"varint,3,opt,name=id_country,json=idCountry,proto3" json:"id_country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_proto_subcription_subcription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subcription_subcription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_proto_subcription_subcription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subscription) GetIdUser() int64 {
	if x != nil {
		return x.IdUser
	}
	return 0
}

func (x *Subscription) GetIdCountry() int64 {
	if x != nil {
		return x.IdCountry
	}
	return 0
}

type Country struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_proto_subcription_subcription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subcription_subcription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_proto_subcription_subcription_proto_rawDescGZIP(), []int{1}
}

func (x *Country) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_subcription_subcription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subcription_subcription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_subcription_subcription_proto_rawDescGZIP(), []int{2}
}

type Get_Countries_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*Country             `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Countries_Response) Reset() {
	*x = Get_Countries_Response{}
	mi := &file_proto_subcription_subcription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Countries_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Countries_Response) ProtoMessage() {}

func (x *Get_Countries_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subcription_subcription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Countries_Response.ProtoReflect.Descriptor instead.
func (*Get_Countries_Response) Descriptor() ([]byte, []int) {
	return file_proto_subcription_subcription_proto_rawDescGZIP(), []int{3}
}

func (x *Get_Countries_Response) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *Get_Countries_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Subscription_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdUser        int64                  `protobuf:"varint,2,opt,name=id_user,json=idUser,proto3" json:"id_user,omitempty"`
	IdCountry     int64                  `protobuf:"varint,3,opt,name=id_country,json=idCountry,proto3" json:"id_country,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription_Request) Reset() {
	*x = Subscription_Request{}
	mi := &file_proto_subcription_subcription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription_Request) ProtoMessage() {}

func (x *Subscription_Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subcription_subcription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription_Request.ProtoReflect.Descriptor instead.
func (*Subscription_Request) Descriptor() ([]byte, []int) {
	return file_proto_subcription_subcription_proto_rawDescGZIP(), []int{4}
}

func (x *Subscription_Request) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Subscription_Request) GetIdUser() int64 {
	if x != nil {
		return x.IdUser
	}
	return 0
}

func (x *Subscription_Request) GetIdCountry() int64 {
	if x != nil {
		return x.IdCountry
	}
	return 0
}

func (x *Subscription_Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Get_Subscription_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Subscription_Response) Reset() {
	*x = Get_Subscription_Response{}
	mi := &file_proto_subcription_subcription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Subscription_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Subscription_Response) ProtoMessage() {}

func (x *Get_Subscription_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subcription_subcription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Subscription_Response.ProtoReflect.Descriptor instead.
func (*Get_Subscription_Response) Descriptor() ([]byte, []int) {
	return file_proto_subcription_subcription_proto_rawDescGZIP(), []int{5}
}

func (x *Get_Subscription_Response) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *Get_Subscription_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Subscription_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription_Response) Reset() {
	*x = Subscription_Response{}
	mi := &file_proto_subcription_subcription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription_Response) ProtoMessage() {}

func (x *Subscription_Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_subcription_subcription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription_Response.ProtoReflect.Descriptor instead.
func (*Subscription_Response) Descriptor() ([]byte, []int) {
	return file_proto_subcription_subcription_proto_rawDescGZIP(), []int{6}
}

func (x *Subscription_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_subcription_subcription_proto protoreflect.FileDescriptor

const file_proto_subcription_subcription_proto_rawDesc = "" +
	"\n" +
	"#proto/subcription/subcription.proto\x12\tsubscribe\"V\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aid_user\x18\x02 \x01(\x03R\x06idUser\x12\x1d\n" +
	"\n" +
	"id_country\x18\x03 \x01(\x03R\tidCountry\"-\n" +
	"\aCountry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\a\n" +
	"\x05Empty\"d\n" +
	"\x16Get_Countries_Response\x120\n" +
	"\tcountries\x18\x01 \x03(\v2\x12.subscribe.CountryR\tcountries\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\x14Subscription_Request\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\aid_user\x18\x02 \x01(\x03R\x06idUser\x12\x1d\n" +
	"\n" +
	"id_country\x18\x03 \x01(\x03R\tidCountry\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"r\n" +
	"\x19Get_Subscription_Response\x12;\n" +
	"\fsubscription\x18\x01 \x01(\v2\x17.subscribe.SubscriptionR\fsubscription\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x15Subscription_Response\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xcb\x03\n" +
	"\x14Subscription_Service\x12D\n" +
	"\rGet_Countries\x12\x10.subscribe.Empty\x1a!.subscribe.Get_Countries_Response\x12X\n" +
	"\x13Create_Subscription\x12\x1f.subscribe.Subscription_Request\x1a .subscribe.Subscription_Response\x12X\n" +
	"\x13Update_Subscription\x12\x1f.subscribe.Subscription_Request\x1a .subscribe.Subscription_Response\x12X\n" +
	"\x13Delete_Subscription\x12\x1f.subscribe.Subscription_Request\x1a .subscribe.Subscription_Response\x12_\n" +
	"\x16Get_Subscription_By_ID\x12\x1f.subscribe.Subscription_Request\x1a$.subscribe.Get_Subscription_ResponseB\tZ\a./protob\x06proto3"

var (
	file_proto_subcription_subcription_proto_rawDescOnce sync.Once
	file_proto_subcription_subcription_proto_rawDescData []byte
)

func file_proto_subcription_subcription_proto_rawDescGZIP() []byte {
	file_proto_subcription_subcription_proto_rawDescOnce.Do(func() {
		file_proto_subcription_subcription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_subcription_subcription_proto_rawDesc), len(file_proto_subcription_subcription_proto_rawDesc)))
	})
	return file_proto_subcription_subcription_proto_rawDescData
}

var file_proto_subcription_subcription_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_subcription_subcription_proto_goTypes = []any{
	(*Subscription)(nil),              // 0: subscribe.Subscription
	(*Country)(nil),                   // 1: subscribe.Country
	(*Empty)(nil),                     // 2: subscribe.Empty
	(*Get_Countries_Response)(nil),    // 3: subscribe.Get_Countries_Response
	(*Subscription_Request)(nil),      // 4: subscribe.Subscription_Request
	(*Get_Subscription_Response)(nil), // 5: subscribe.Get_Subscription_Response
	(*Subscription_Response)(nil),     // 6: subscribe.Subscription_Response
}
var file_proto_subcription_subcription_proto_depIdxs = []int32{
	1, // 0: subscribe.Get_Countries_Response.countries:type_name -> subscribe.Country
	0, // 1: subscribe.Get_Subscription_Response.subscription:type_name -> subscribe.Subscription
	2, // 2: subscribe.Subscription_Service.Get_Countries:input_type -> subscribe.Empty
	4, // 3: subscribe.Subscription_Service.Create_Subscription:input_type -> subscribe.Subscription_Request
	4, // 4: subscribe.Subscription_Service.Update_Subscription:input_type -> subscribe.Subscription_Request
	4, // 5: subscribe.Subscription_Service.Delete_Subscription:input_type -> subscribe.Subscription_Request
	4, // 6: subscribe.Subscription_Service.Get_Subscription_By_ID:input_type -> subscribe.Subscription_Request
	3, // 7: subscribe.Subscription_Service.Get_Countries:output_type -> subscribe.Get_Countries_Response
	6, // 8: subscribe.Subscription_Service.Create_Subscription:output_type -> subscribe.Subscription_Response
	6, // 9: subscribe.Subscription_Service.Update_Subscription:output_type -> subscribe.Subscription_Response
	6, // 10: subscribe.Subscription_Service.Delete_Subscription:output_type -> subscribe.Subscription_Response
	5, // 11: subscribe.Subscription_Service.Get_Subscription_By_ID:output_type -> subscribe.Get_Subscription_Response
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_subcription_subcription_proto_init() }
func file_proto_subcription_subcription_proto_init() {
	if File_proto_subcription_subcription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_subcription_subcription_proto_rawDesc), len(file_proto_subcription_subcription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_subcription_subcription_proto_goTypes,
		DependencyIndexes: file_proto_subcription_subcription_proto_depIdxs,
		MessageInfos:      file_proto_subcription_subcription_proto_msgTypes,
	}.Build()
	File_proto_subcription_subcription_proto = out.File
	file_proto_subcription_subcription_proto_goTypes = nil
	file_proto_subcription_subcription_proto_depIdxs = nil
}
