// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: subcription/subcription.proto

package subscriptionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Subscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdUser        string                 `protobuf:"bytes,2,opt,name=id_user,json=idUser,proto3" json:"id_user,omitempty"`
	IdCountry     string                 `protobuf:"bytes,3,opt,name=id_country,json=idCountry,proto3" json:"id_country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_subcription_subcription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_subcription_subcription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_subcription_subcription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetIdUser() string {
	if x != nil {
		return x.IdUser
	}
	return ""
}

func (x *Subscription) GetIdCountry() string {
	if x != nil {
		return x.IdCountry
	}
	return ""
}

type Country struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IpcPhase                  string                 `protobuf:"bytes,3,opt,name=ipc_phase,json=ipcPhase,proto3" json:"ipc_phase,omitempty"`
	PopulationInPhase         int64                  `protobuf:"varint,4,opt,name=population_in_phase,json=populationInPhase,proto3" json:"population_in_phase,omitempty"`
	PopulationFractionInPhase float64                `protobuf:"fixed64,5,opt,name=population_fraction_in_phase,json=populationFractionInPhase,proto3" json:"population_fraction_in_phase,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Country) Reset() {
	*x = Country{}
	mi := &file_subcription_subcription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Country) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Country) ProtoMessage() {}

func (x *Country) ProtoReflect() protoreflect.Message {
	mi := &file_subcription_subcription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Country.ProtoReflect.Descriptor instead.
func (*Country) Descriptor() ([]byte, []int) {
	return file_subcription_subcription_proto_rawDescGZIP(), []int{1}
}

func (x *Country) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Country) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Country) GetIpcPhase() string {
	if x != nil {
		return x.IpcPhase
	}
	return ""
}

func (x *Country) GetPopulationInPhase() int64 {
	if x != nil {
		return x.PopulationInPhase
	}
	return 0
}

func (x *Country) GetPopulationFractionInPhase() float64 {
	if x != nil {
		return x.PopulationFractionInPhase
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_subcription_subcription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_subcription_subcription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_subcription_subcription_proto_rawDescGZIP(), []int{2}
}

type Get_Countries_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*Country             `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Countries_Response) Reset() {
	*x = Get_Countries_Response{}
	mi := &file_subcription_subcription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Countries_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Countries_Response) ProtoMessage() {}

func (x *Get_Countries_Response) ProtoReflect() protoreflect.Message {
	mi := &file_subcription_subcription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Countries_Response.ProtoReflect.Descriptor instead.
func (*Get_Countries_Response) Descriptor() ([]byte, []int) {
	return file_subcription_subcription_proto_rawDescGZIP(), []int{3}
}

func (x *Get_Countries_Response) GetCountries() []*Country {
	if x != nil {
		return x.Countries
	}
	return nil
}

func (x *Get_Countries_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Subscription_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IdUser        string                 `protobuf:"bytes,2,opt,name=id_user,json=idUser,proto3" json:"id_user,omitempty"`
	IdCountry     string                 `protobuf:"bytes,3,opt,name=id_country,json=idCountry,proto3" json:"id_country,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription_Request) Reset() {
	*x = Subscription_Request{}
	mi := &file_subcription_subcription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription_Request) ProtoMessage() {}

func (x *Subscription_Request) ProtoReflect() protoreflect.Message {
	mi := &file_subcription_subcription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription_Request.ProtoReflect.Descriptor instead.
func (*Subscription_Request) Descriptor() ([]byte, []int) {
	return file_subcription_subcription_proto_rawDescGZIP(), []int{4}
}

func (x *Subscription_Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription_Request) GetIdUser() string {
	if x != nil {
		return x.IdUser
	}
	return ""
}

func (x *Subscription_Request) GetIdCountry() string {
	if x != nil {
		return x.IdCountry
	}
	return ""
}

func (x *Subscription_Request) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Get_Subscription_BY_ID_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  []*Subscription        `protobuf:"bytes,1,rep,name=subscription,proto3" json:"subscription,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Subscription_BY_ID_Response) Reset() {
	*x = Get_Subscription_BY_ID_Response{}
	mi := &file_subcription_subcription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Subscription_BY_ID_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Subscription_BY_ID_Response) ProtoMessage() {}

func (x *Get_Subscription_BY_ID_Response) ProtoReflect() protoreflect.Message {
	mi := &file_subcription_subcription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Subscription_BY_ID_Response.ProtoReflect.Descriptor instead.
func (*Get_Subscription_BY_ID_Response) Descriptor() ([]byte, []int) {
	return file_subcription_subcription_proto_rawDescGZIP(), []int{5}
}

func (x *Get_Subscription_BY_ID_Response) GetSubscription() []*Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *Get_Subscription_BY_ID_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Get_Subscription_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  *Subscription          `protobuf:"bytes,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Get_Subscription_Response) Reset() {
	*x = Get_Subscription_Response{}
	mi := &file_subcription_subcription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Get_Subscription_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get_Subscription_Response) ProtoMessage() {}

func (x *Get_Subscription_Response) ProtoReflect() protoreflect.Message {
	mi := &file_subcription_subcription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get_Subscription_Response.ProtoReflect.Descriptor instead.
func (*Get_Subscription_Response) Descriptor() ([]byte, []int) {
	return file_subcription_subcription_proto_rawDescGZIP(), []int{6}
}

func (x *Get_Subscription_Response) GetSubscription() *Subscription {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *Get_Subscription_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Subscription_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subscription_Response) Reset() {
	*x = Subscription_Response{}
	mi := &file_subcription_subcription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription_Response) ProtoMessage() {}

func (x *Subscription_Response) ProtoReflect() protoreflect.Message {
	mi := &file_subcription_subcription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription_Response.ProtoReflect.Descriptor instead.
func (*Subscription_Response) Descriptor() ([]byte, []int) {
	return file_subcription_subcription_proto_rawDescGZIP(), []int{7}
}

func (x *Subscription_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_subcription_subcription_proto protoreflect.FileDescriptor

const file_subcription_subcription_proto_rawDesc = "" +
	"\n" +
	"\x1dsubcription/subcription.proto\x12\fsubscribe.v1\"V\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aid_user\x18\x02 \x01(\tR\x06idUser\x12\x1d\n" +
	"\n" +
	"id_country\x18\x03 \x01(\tR\tidCountry\"\xbb\x01\n" +
	"\aCountry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tipc_phase\x18\x03 \x01(\tR\bipcPhase\x12.\n" +
	"\x13population_in_phase\x18\x04 \x01(\x03R\x11populationInPhase\x12?\n" +
	"\x1cpopulation_fraction_in_phase\x18\x05 \x01(\x01R\x19populationFractionInPhase\"\a\n" +
	"\x05Empty\"g\n" +
	"\x16Get_Countries_Response\x123\n" +
	"\tcountries\x18\x01 \x03(\v2\x15.subscribe.v1.CountryR\tcountries\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"x\n" +
	"\x14Subscription_Request\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aid_user\x18\x02 \x01(\tR\x06idUser\x12\x1d\n" +
	"\n" +
	"id_country\x18\x03 \x01(\tR\tidCountry\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"{\n" +
	"\x1fGet_Subscription_BY_ID_Response\x12>\n" +
	"\fsubscription\x18\x01 \x03(\v2\x1a.subscribe.v1.SubscriptionR\fsubscription\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"u\n" +
	"\x19Get_Subscription_Response\x12>\n" +
	"\fsubscription\x18\x01 \x01(\v2\x1a.subscribe.v1.SubscriptionR\fsubscription\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x15Subscription_Response\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xef\x03\n" +
	"\x14Subscription_Service\x12J\n" +
	"\rGet_Countries\x12\x13.subscribe.v1.Empty\x1a$.subscribe.v1.Get_Countries_Response\x12^\n" +
	"\x13Create_Subscription\x12\".subscribe.v1.Subscription_Request\x1a#.subscribe.v1.Subscription_Response\x12^\n" +
	"\x13Update_Subscription\x12\".subscribe.v1.Subscription_Request\x1a#.subscribe.v1.Subscription_Response\x12^\n" +
	"\x13Delete_Subscription\x12\".subscribe.v1.Subscription_Request\x1a#.subscribe.v1.Subscription_Response\x12k\n" +
	"\x16Get_Subscription_By_ID\x12\".subscribe.v1.Subscription_Request\x1a-.subscribe.v1.Get_Subscription_BY_ID_ResponseB-Z+hunger4data/pb/subscriptionv;subscriptionv1b\x06proto3"

var (
	file_subcription_subcription_proto_rawDescOnce sync.Once
	file_subcription_subcription_proto_rawDescData []byte
)

func file_subcription_subcription_proto_rawDescGZIP() []byte {
	file_subcription_subcription_proto_rawDescOnce.Do(func() {
		file_subcription_subcription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subcription_subcription_proto_rawDesc), len(file_subcription_subcription_proto_rawDesc)))
	})
	return file_subcription_subcription_proto_rawDescData
}

var file_subcription_subcription_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_subcription_subcription_proto_goTypes = []any{
	(*Subscription)(nil),                    // 0: subscribe.v1.Subscription
	(*Country)(nil),                         // 1: subscribe.v1.Country
	(*Empty)(nil),                           // 2: subscribe.v1.Empty
	(*Get_Countries_Response)(nil),          // 3: subscribe.v1.Get_Countries_Response
	(*Subscription_Request)(nil),            // 4: subscribe.v1.Subscription_Request
	(*Get_Subscription_BY_ID_Response)(nil), // 5: subscribe.v1.Get_Subscription_BY_ID_Response
	(*Get_Subscription_Response)(nil),       // 6: subscribe.v1.Get_Subscription_Response
	(*Subscription_Response)(nil),           // 7: subscribe.v1.Subscription_Response
}
var file_subcription_subcription_proto_depIdxs = []int32{
	1, // 0: subscribe.v1.Get_Countries_Response.countries:type_name -> subscribe.v1.Country
	0, // 1: subscribe.v1.Get_Subscription_BY_ID_Response.subscription:type_name -> subscribe.v1.Subscription
	0, // 2: subscribe.v1.Get_Subscription_Response.subscription:type_name -> subscribe.v1.Subscription
	2, // 3: subscribe.v1.Subscription_Service.Get_Countries:input_type -> subscribe.v1.Empty
	4, // 4: subscribe.v1.Subscription_Service.Create_Subscription:input_type -> subscribe.v1.Subscription_Request
	4, // 5: subscribe.v1.Subscription_Service.Update_Subscription:input_type -> subscribe.v1.Subscription_Request
	4, // 6: subscribe.v1.Subscription_Service.Delete_Subscription:input_type -> subscribe.v1.Subscription_Request
	4, // 7: subscribe.v1.Subscription_Service.Get_Subscription_By_ID:input_type -> subscribe.v1.Subscription_Request
	3, // 8: subscribe.v1.Subscription_Service.Get_Countries:output_type -> subscribe.v1.Get_Countries_Response
	7, // 9: subscribe.v1.Subscription_Service.Create_Subscription:output_type -> subscribe.v1.Subscription_Response
	7, // 10: subscribe.v1.Subscription_Service.Update_Subscription:output_type -> subscribe.v1.Subscription_Response
	7, // 11: subscribe.v1.Subscription_Service.Delete_Subscription:output_type -> subscribe.v1.Subscription_Response
	5, // 12: subscribe.v1.Subscription_Service.Get_Subscription_By_ID:output_type -> subscribe.v1.Get_Subscription_BY_ID_Response
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_subcription_subcription_proto_init() }
func file_subcription_subcription_proto_init() {
	if File_subcription_subcription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subcription_subcription_proto_rawDesc), len(file_subcription_subcription_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subcription_subcription_proto_goTypes,
		DependencyIndexes: file_subcription_subcription_proto_depIdxs,
		MessageInfos:      file_subcription_subcription_proto_msgTypes,
	}.Build()
	File_subcription_subcription_proto = out.File
	file_subcription_subcription_proto_goTypes = nil
	file_subcription_subcription_proto_depIdxs = nil
}
