// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: subcription.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Subscription_Service_Get_Countries_FullMethodName          = "/subscribe.Subscription_Service/Get_Countries"
	Subscription_Service_Create_Subscription_FullMethodName    = "/subscribe.Subscription_Service/Create_Subscription"
	Subscription_Service_Update_Subscription_FullMethodName    = "/subscribe.Subscription_Service/Update_Subscription"
	Subscription_Service_Delete_Subscription_FullMethodName    = "/subscribe.Subscription_Service/Delete_Subscription"
	Subscription_Service_Get_Subscription_By_ID_FullMethodName = "/subscribe.Subscription_Service/Get_Subscription_By_ID"
)

// Subscription_ServiceClient is the client API for Subscription_Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Subscription_ServiceClient interface {
	Get_Countries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Get_Countries_Response, error)
	Create_Subscription(ctx context.Context, in *Subscription_Request, opts ...grpc.CallOption) (*Subscription_Response, error)
	Update_Subscription(ctx context.Context, in *Subscription_Request, opts ...grpc.CallOption) (*Subscription_Response, error)
	Delete_Subscription(ctx context.Context, in *Subscription_Request, opts ...grpc.CallOption) (*Subscription_Response, error)
	Get_Subscription_By_ID(ctx context.Context, in *Subscription_Request, opts ...grpc.CallOption) (*Get_Subscription_BY_ID_Response, error)
}

type subscription_ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscription_ServiceClient(cc grpc.ClientConnInterface) Subscription_ServiceClient {
	return &subscription_ServiceClient{cc}
}

func (c *subscription_ServiceClient) Get_Countries(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Get_Countries_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_Countries_Response)
	err := c.cc.Invoke(ctx, Subscription_Service_Get_Countries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscription_ServiceClient) Create_Subscription(ctx context.Context, in *Subscription_Request, opts ...grpc.CallOption) (*Subscription_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subscription_Response)
	err := c.cc.Invoke(ctx, Subscription_Service_Create_Subscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscription_ServiceClient) Update_Subscription(ctx context.Context, in *Subscription_Request, opts ...grpc.CallOption) (*Subscription_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subscription_Response)
	err := c.cc.Invoke(ctx, Subscription_Service_Update_Subscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscription_ServiceClient) Delete_Subscription(ctx context.Context, in *Subscription_Request, opts ...grpc.CallOption) (*Subscription_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subscription_Response)
	err := c.cc.Invoke(ctx, Subscription_Service_Delete_Subscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *subscription_ServiceClient) Get_Subscription_By_ID(ctx context.Context, in *Subscription_Request, opts ...grpc.CallOption) (*Get_Subscription_BY_ID_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Get_Subscription_BY_ID_Response)
	err := c.cc.Invoke(ctx, Subscription_Service_Get_Subscription_By_ID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Subscription_ServiceServer is the server API for Subscription_Service service.
// All implementations must embed UnimplementedSubscription_ServiceServer
// for forward compatibility.
type Subscription_ServiceServer interface {
	Get_Countries(context.Context, *Empty) (*Get_Countries_Response, error)
	Create_Subscription(context.Context, *Subscription_Request) (*Subscription_Response, error)
	Update_Subscription(context.Context, *Subscription_Request) (*Subscription_Response, error)
	Delete_Subscription(context.Context, *Subscription_Request) (*Subscription_Response, error)
	Get_Subscription_By_ID(context.Context, *Subscription_Request) (*Get_Subscription_BY_ID_Response, error)
	mustEmbedUnimplementedSubscription_ServiceServer()
}

// UnimplementedSubscription_ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSubscription_ServiceServer struct{}

func (UnimplementedSubscription_ServiceServer) Get_Countries(context.Context, *Empty) (*Get_Countries_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_Countries not implemented")
}
func (UnimplementedSubscription_ServiceServer) Create_Subscription(context.Context, *Subscription_Request) (*Subscription_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Create_Subscription not implemented")
}
func (UnimplementedSubscription_ServiceServer) Update_Subscription(context.Context, *Subscription_Request) (*Subscription_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Update_Subscription not implemented")
}
func (UnimplementedSubscription_ServiceServer) Delete_Subscription(context.Context, *Subscription_Request) (*Subscription_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete_Subscription not implemented")
}
func (UnimplementedSubscription_ServiceServer) Get_Subscription_By_ID(context.Context, *Subscription_Request) (*Get_Subscription_BY_ID_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Get_Subscription_By_ID not implemented")
}
func (UnimplementedSubscription_ServiceServer) mustEmbedUnimplementedSubscription_ServiceServer() {}
func (UnimplementedSubscription_ServiceServer) testEmbeddedByValue()                              {}

// UnsafeSubscription_ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Subscription_ServiceServer will
// result in compilation errors.
type UnsafeSubscription_ServiceServer interface {
	mustEmbedUnimplementedSubscription_ServiceServer()
}

func RegisterSubscription_ServiceServer(s grpc.ServiceRegistrar, srv Subscription_ServiceServer) {
	// If the following call panics, it indicates UnimplementedSubscription_ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Subscription_Service_ServiceDesc, srv)
}

func _Subscription_Service_Get_Countries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Subscription_ServiceServer).Get_Countries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_Service_Get_Countries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Subscription_ServiceServer).Get_Countries(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_Service_Create_Subscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Subscription_ServiceServer).Create_Subscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_Service_Create_Subscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Subscription_ServiceServer).Create_Subscription(ctx, req.(*Subscription_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_Service_Update_Subscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Subscription_ServiceServer).Update_Subscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_Service_Update_Subscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Subscription_ServiceServer).Update_Subscription(ctx, req.(*Subscription_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_Service_Delete_Subscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Subscription_ServiceServer).Delete_Subscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_Service_Delete_Subscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Subscription_ServiceServer).Delete_Subscription(ctx, req.(*Subscription_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _Subscription_Service_Get_Subscription_By_ID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Subscription_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Subscription_ServiceServer).Get_Subscription_By_ID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Subscription_Service_Get_Subscription_By_ID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Subscription_ServiceServer).Get_Subscription_By_ID(ctx, req.(*Subscription_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Subscription_Service_ServiceDesc is the grpc.ServiceDesc for Subscription_Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Subscription_Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "subscribe.Subscription_Service",
	HandlerType: (*Subscription_ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get_Countries",
			Handler:    _Subscription_Service_Get_Countries_Handler,
		},
		{
			MethodName: "Create_Subscription",
			Handler:    _Subscription_Service_Create_Subscription_Handler,
		},
		{
			MethodName: "Update_Subscription",
			Handler:    _Subscription_Service_Update_Subscription_Handler,
		},
		{
			MethodName: "Delete_Subscription",
			Handler:    _Subscription_Service_Delete_Subscription_Handler,
		},
		{
			MethodName: "Get_Subscription_By_ID",
			Handler:    _Subscription_Service_Get_Subscription_By_ID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subcription.proto",
}
