syntax = "proto3";
package subscribe.v1;
option go_package = "hunger4data/pb/subscriptionv;subscriptionv1";

message Subscription {
  string id = 1;
  string user_id = 2;
  string country_code = 3;
}

message Country {
  int64 id = 1;
  string name  = 2;
  string ipc_phase = 3;
  int64 population_in_phase = 4;
  double population_fraction_in_phase = 5;
  string location_code = 6;
}

service Subscription_Service {
  rpc Get_Countries(Empty) returns (Get_Countries_Response);
  rpc Create_Subscription(Subscription_Request) returns (Subscription_Response);
  rpc Update_Subscription(Subscription_Request) returns (Subscription_Response);
  rpc Delete_Subscription(Subscription_Request) returns (Subscription_Response);
  rpc Get_Subscriptions(Subscription_Request) returns (Get_Subscriptions_Response);
}

message Empty {}

message Get_Countries_Response {
  repeated Country countries = 1;
  string message = 2;
}

message Subscription_Request {
  string id = 1;
  string user_id = 2;
  string country_code = 3;
  string message = 4;
}

message Get_Subscriptions_Response {
  repeated Subscription subscription = 1;
  string message = 2;
}

message Get_Subscription_Response {
  Subscription subscription = 1;
  string message = 2;
}

message Subscription_Response {
  string message = 1;
}
