// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockery

import (
	repo "authenticator/internal/adapters/repo"

	mock "github.com/stretchr/testify/mock"
)

// MockAuthFunc is an autogenerated mock type for the AuthFunc type
type MockAuthFunc struct {
	mock.Mock
}

type MockAuthFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthFunc) EXPECT() *MockAuthFunc_Expecter {
	return &MockAuthFunc_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: username, password
func (_m *MockAuthFunc) Login(username string, password string) (string, error) {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthFunc_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthFunc_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockAuthFunc_Expecter) Login(username interface{}, password interface{}) *MockAuthFunc_Login_Call {
	return &MockAuthFunc_Login_Call{Call: _e.mock.On("Login", username, password)}
}

func (_c *MockAuthFunc_Login_Call) Run(run func(username string, password string)) *MockAuthFunc_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuthFunc_Login_Call) Return(_a0 string, _a1 error) *MockAuthFunc_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthFunc_Login_Call) RunAndReturn(run func(string, string) (string, error)) *MockAuthFunc_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: username, password
func (_m *MockAuthFunc) Register(username string, password string) (*repo.User, error) {
	ret := _m.Called(username, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*repo.User, error)); ok {
		return rf(username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *repo.User); ok {
		r0 = rf(username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthFunc_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthFunc_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - username string
//   - password string
func (_e *MockAuthFunc_Expecter) Register(username interface{}, password interface{}) *MockAuthFunc_Register_Call {
	return &MockAuthFunc_Register_Call{Call: _e.mock.On("Register", username, password)}
}

func (_c *MockAuthFunc_Register_Call) Run(run func(username string, password string)) *MockAuthFunc_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuthFunc_Register_Call) Return(_a0 *repo.User, _a1 error) *MockAuthFunc_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthFunc_Register_Call) RunAndReturn(run func(string, string) (*repo.User, error)) *MockAuthFunc_Register_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthFunc creates a new instance of MockAuthFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthFunc {
	mock := &MockAuthFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
