// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockery

import (
	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockCryptofuncs is an autogenerated mock type for the Cryptofuncs type
type MockCryptofuncs struct {
	mock.Mock
}

type MockCryptofuncs_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCryptofuncs) EXPECT() *MockCryptofuncs_Expecter {
	return &MockCryptofuncs_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function with given fields: user_ID
func (_m *MockCryptofuncs) GenerateToken(user_ID uuid.UUID) (string, error) {
	ret := _m.Called(user_ID)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (string, error)); ok {
		return rf(user_ID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) string); ok {
		r0 = rf(user_ID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(user_ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptofuncs_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockCryptofuncs_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - user_ID uuid.UUID
func (_e *MockCryptofuncs_Expecter) GenerateToken(user_ID interface{}) *MockCryptofuncs_GenerateToken_Call {
	return &MockCryptofuncs_GenerateToken_Call{Call: _e.mock.On("GenerateToken", user_ID)}
}

func (_c *MockCryptofuncs_GenerateToken_Call) Run(run func(user_ID uuid.UUID)) *MockCryptofuncs_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockCryptofuncs_GenerateToken_Call) Return(_a0 string, _a1 error) *MockCryptofuncs_GenerateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptofuncs_GenerateToken_Call) RunAndReturn(run func(uuid.UUID) (string, error)) *MockCryptofuncs_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// PassCompare provides a mock function with given fields: pass, hash
func (_m *MockCryptofuncs) PassCompare(pass string, hash string) bool {
	ret := _m.Called(pass, hash)

	if len(ret) == 0 {
		panic("no return value specified for PassCompare")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(pass, hash)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockCryptofuncs_PassCompare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PassCompare'
type MockCryptofuncs_PassCompare_Call struct {
	*mock.Call
}

// PassCompare is a helper method to define mock.On call
//   - pass string
//   - hash string
func (_e *MockCryptofuncs_Expecter) PassCompare(pass interface{}, hash interface{}) *MockCryptofuncs_PassCompare_Call {
	return &MockCryptofuncs_PassCompare_Call{Call: _e.mock.On("PassCompare", pass, hash)}
}

func (_c *MockCryptofuncs_PassCompare_Call) Run(run func(pass string, hash string)) *MockCryptofuncs_PassCompare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockCryptofuncs_PassCompare_Call) Return(_a0 bool) *MockCryptofuncs_PassCompare_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCryptofuncs_PassCompare_Call) RunAndReturn(run func(string, string) bool) *MockCryptofuncs_PassCompare_Call {
	_c.Call.Return(run)
	return _c
}

// PassHash provides a mock function with given fields: pass
func (_m *MockCryptofuncs) PassHash(pass string) (string, error) {
	ret := _m.Called(pass)

	if len(ret) == 0 {
		panic("no return value specified for PassHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(pass)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(pass)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pass)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCryptofuncs_PassHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PassHash'
type MockCryptofuncs_PassHash_Call struct {
	*mock.Call
}

// PassHash is a helper method to define mock.On call
//   - pass string
func (_e *MockCryptofuncs_Expecter) PassHash(pass interface{}) *MockCryptofuncs_PassHash_Call {
	return &MockCryptofuncs_PassHash_Call{Call: _e.mock.On("PassHash", pass)}
}

func (_c *MockCryptofuncs_PassHash_Call) Run(run func(pass string)) *MockCryptofuncs_PassHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCryptofuncs_PassHash_Call) Return(_a0 string, _a1 error) *MockCryptofuncs_PassHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCryptofuncs_PassHash_Call) RunAndReturn(run func(string) (string, error)) *MockCryptofuncs_PassHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCryptofuncs creates a new instance of MockCryptofuncs. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCryptofuncs(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCryptofuncs {
	mock := &MockCryptofuncs{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
