// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockery

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	repo "authenticator/internal/adapters/repo"
)

// MockMailer is an autogenerated mock type for the Mailer type
type MockMailer struct {
	mock.Mock
}

type MockMailer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMailer) EXPECT() *MockMailer_Expecter {
	return &MockMailer_Expecter{mock: &_m.Mock}
}

// SendRegistrationActivationLink provides a mock function with given fields: ctx, u
func (_m *MockMailer) SendRegistrationActivationLink(ctx context.Context, u *repo.User) error {
	ret := _m.Called(ctx, u)

	if len(ret) == 0 {
		panic("no return value specified for SendRegistrationActivationLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *repo.User) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMailer_SendRegistrationActivationLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendRegistrationActivationLink'
type MockMailer_SendRegistrationActivationLink_Call struct {
	*mock.Call
}

// SendRegistrationActivationLink is a helper method to define mock.On call
//   - ctx context.Context
//   - u *repo.User
func (_e *MockMailer_Expecter) SendRegistrationActivationLink(ctx interface{}, u interface{}) *MockMailer_SendRegistrationActivationLink_Call {
	return &MockMailer_SendRegistrationActivationLink_Call{Call: _e.mock.On("SendRegistrationActivationLink", ctx, u)}
}

func (_c *MockMailer_SendRegistrationActivationLink_Call) Run(run func(ctx context.Context, u *repo.User)) *MockMailer_SendRegistrationActivationLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*repo.User))
	})
	return _c
}

func (_c *MockMailer_SendRegistrationActivationLink_Call) Return(_a0 error) *MockMailer_SendRegistrationActivationLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMailer_SendRegistrationActivationLink_Call) RunAndReturn(run func(context.Context, *repo.User) error) *MockMailer_SendRegistrationActivationLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMailer creates a new instance of MockMailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMailer {
	mock := &MockMailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
