// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockery

import (
	repo "authenticator/internal/adapters/repo"

	mock "github.com/stretchr/testify/mock"
)

// MockUserRepo is an autogenerated mock type for the UserRepo type
type MockUserRepo struct {
	mock.Mock
}

type MockUserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepo) EXPECT() *MockUserRepo_Expecter {
	return &MockUserRepo_Expecter{mock: &_m.Mock}
}

// ActivateUser provides a mock function with given fields: activationString
func (_m *MockUserRepo) ActivateUser(activationString string) error {
	ret := _m.Called(activationString)

	if len(ret) == 0 {
		panic("no return value specified for ActivateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(activationString)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_ActivateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivateUser'
type MockUserRepo_ActivateUser_Call struct {
	*mock.Call
}

// ActivateUser is a helper method to define mock.On call
//   - activationString string
func (_e *MockUserRepo_Expecter) ActivateUser(activationString interface{}) *MockUserRepo_ActivateUser_Call {
	return &MockUserRepo_ActivateUser_Call{Call: _e.mock.On("ActivateUser", activationString)}
}

func (_c *MockUserRepo_ActivateUser_Call) Run(run func(activationString string)) *MockUserRepo_ActivateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepo_ActivateUser_Call) Return(_a0 error) *MockUserRepo_ActivateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_ActivateUser_Call) RunAndReturn(run func(string) error) *MockUserRepo_ActivateUser_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: u
func (_m *MockUserRepo) CreateUser(u repo.User) error {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(repo.User) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - u repo.User
func (_e *MockUserRepo_Expecter) CreateUser(u interface{}) *MockUserRepo_CreateUser_Call {
	return &MockUserRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", u)}
}

func (_c *MockUserRepo_CreateUser_Call) Run(run func(u repo.User)) *MockUserRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(repo.User))
	})
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) Return(_a0 error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_CreateUser_Call) RunAndReturn(run func(repo.User) error) *MockUserRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: username
func (_m *MockUserRepo) DeleteUser(username string) error {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(username)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserRepo_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - username string
func (_e *MockUserRepo_Expecter) DeleteUser(username interface{}) *MockUserRepo_DeleteUser_Call {
	return &MockUserRepo_DeleteUser_Call{Call: _e.mock.On("DeleteUser", username)}
}

func (_c *MockUserRepo_DeleteUser_Call) Run(run func(username string)) *MockUserRepo_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepo_DeleteUser_Call) Return(_a0 error) *MockUserRepo_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_DeleteUser_Call) RunAndReturn(run func(string) error) *MockUserRepo_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUsername provides a mock function with given fields: username
func (_m *MockUserRepo) GetByUsername(username string) (*repo.User, error) {
	ret := _m.Called(username)

	if len(ret) == 0 {
		panic("no return value specified for GetByUsername")
	}

	var r0 *repo.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*repo.User, error)); ok {
		return rf(username)
	}
	if rf, ok := ret.Get(0).(func(string) *repo.User); ok {
		r0 = rf(username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*repo.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserRepo_GetByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUsername'
type MockUserRepo_GetByUsername_Call struct {
	*mock.Call
}

// GetByUsername is a helper method to define mock.On call
//   - username string
func (_e *MockUserRepo_Expecter) GetByUsername(username interface{}) *MockUserRepo_GetByUsername_Call {
	return &MockUserRepo_GetByUsername_Call{Call: _e.mock.On("GetByUsername", username)}
}

func (_c *MockUserRepo_GetByUsername_Call) Run(run func(username string)) *MockUserRepo_GetByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockUserRepo_GetByUsername_Call) Return(_a0 *repo.User, _a1 error) *MockUserRepo_GetByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserRepo_GetByUsername_Call) RunAndReturn(run func(string) (*repo.User, error)) *MockUserRepo_GetByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function with given fields: username, user
func (_m *MockUserRepo) UpdateUser(username string, user repo.User) error {
	ret := _m.Called(username, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, repo.User) error); ok {
		r0 = rf(username, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUserRepo_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserRepo_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - username string
//   - user repo.User
func (_e *MockUserRepo_Expecter) UpdateUser(username interface{}, user interface{}) *MockUserRepo_UpdateUser_Call {
	return &MockUserRepo_UpdateUser_Call{Call: _e.mock.On("UpdateUser", username, user)}
}

func (_c *MockUserRepo_UpdateUser_Call) Run(run func(username string, user repo.User)) *MockUserRepo_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(repo.User))
	})
	return _c
}

func (_c *MockUserRepo_UpdateUser_Call) Return(_a0 error) *MockUserRepo_UpdateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUserRepo_UpdateUser_Call) RunAndReturn(run func(string, repo.User) error) *MockUserRepo_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepo creates a new instance of MockUserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepo {
	mock := &MockUserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
