// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	db "payment-service/internal/adapters/db"

	mock "github.com/stretchr/testify/mock"
)

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// SendCheckoutURL provides a mock function with given fields: ctx, p, url
func (_m *Mailer) SendCheckoutURL(ctx context.Context, p *db.Payment, url string) error {
	ret := _m.Called(ctx, p, url)

	if len(ret) == 0 {
		panic("no return value specified for SendCheckoutURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.Payment, string) error); ok {
		r0 = rf(ctx, p, url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailer creates a new instance of Mailer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mailer {
	mock := &Mailer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
