// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	db "payment-service/internal/adapters/db"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PaymentRepo is an autogenerated mock type for the PaymentRepo type
type PaymentRepo struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: ctx, p
func (_m *PaymentRepo) CreatePayment(ctx context.Context, p *db.Payment) (*db.Payment, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 *db.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *db.Payment) (*db.Payment, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *db.Payment) *db.Payment); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *db.Payment) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindPaymentByID provides a mock function with given fields: ctx, id
func (_m *PaymentRepo) FindPaymentByID(ctx context.Context, id uuid.UUID) (*db.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindPaymentByID")
	}

	var r0 *db.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*db.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *db.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserPaymentByID provides a mock function with given fields: ctx, userId, paymentId
func (_m *PaymentRepo) FindUserPaymentByID(ctx context.Context, userId uuid.UUID, paymentId uuid.UUID) (*db.Payment, error) {
	ret := _m.Called(ctx, userId, paymentId)

	if len(ret) == 0 {
		panic("no return value specified for FindUserPaymentByID")
	}

	var r0 *db.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*db.Payment, error)); ok {
		return rf(ctx, userId, paymentId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *db.Payment); ok {
		r0 = rf(ctx, userId, paymentId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, userId, paymentId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByUser provides a mock function with given fields: ctx, userID
func (_m *PaymentRepo) ListByUser(ctx context.Context, userID uuid.UUID) ([]db.Payment, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []db.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.Payment, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.Payment); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListPendingByUser provides a mock function with given fields: ctx, userID
func (_m *PaymentRepo) ListPendingByUser(ctx context.Context, userID uuid.UUID) ([]db.Payment, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListPendingByUser")
	}

	var r0 []db.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.Payment, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.Payment); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePayment provides a mock function with given fields: ctx, id, status, eventType, sessionID, source, providerEventID
func (_m *PaymentRepo) UpdatePayment(ctx context.Context, id uuid.UUID, status db.PaymentStatus, eventType db.PaymentEventType, sessionID string, source string, providerEventID string) (*db.Payment, error) {
	ret := _m.Called(ctx, id, status, eventType, sessionID, source, providerEventID)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePayment")
	}

	var r0 *db.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, db.PaymentStatus, db.PaymentEventType, string, string, string) (*db.Payment, error)); ok {
		return rf(ctx, id, status, eventType, sessionID, source, providerEventID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, db.PaymentStatus, db.PaymentEventType, string, string, string) *db.Payment); ok {
		r0 = rf(ctx, id, status, eventType, sessionID, source, providerEventID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, db.PaymentStatus, db.PaymentEventType, string, string, string) error); ok {
		r1 = rf(ctx, id, status, eventType, sessionID, source, providerEventID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentRepo creates a new instance of PaymentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepo {
	mock := &PaymentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
