// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"
	stripeAdapter "payment-service/internal/adapters/stripe"

	mock "github.com/stretchr/testify/mock"
)

// StripeAdapter is an autogenerated mock type for the StripeAdapter type
type StripeAdapter struct {
	mock.Mock
}

// CreateCheckoutSession provides a mock function with given fields: ctx, input
func (_m *StripeAdapter) CreateCheckoutSession(ctx context.Context, input stripeAdapter.CreateCheckoutSessionInput) (*stripeAdapter.CheckoutSessionResult, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateCheckoutSession")
	}

	var r0 *stripeAdapter.CheckoutSessionResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, stripeAdapter.CreateCheckoutSessionInput) (*stripeAdapter.CheckoutSessionResult, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, stripeAdapter.CreateCheckoutSessionInput) *stripeAdapter.CheckoutSessionResult); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*stripeAdapter.CheckoutSessionResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, stripeAdapter.CreateCheckoutSessionInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCheckoutSessionURL provides a mock function with given fields: ctx, sessionID
func (_m *StripeAdapter) GetCheckoutSessionURL(ctx context.Context, sessionID string) (string, error) {
	ret := _m.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetCheckoutSessionURL")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, sessionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStripeAdapter creates a new instance of StripeAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStripeAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *StripeAdapter {
	mock := &StripeAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
