// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockery

import (
	model "subscription/internal/adapters/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSubServ is an autogenerated mock type for the SubServ type
type MockSubServ struct {
	mock.Mock
}

type MockSubServ_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubServ) EXPECT() *MockSubServ_Expecter {
	return &MockSubServ_Expecter{mock: &_m.Mock}
}

// CreateSubcription provides a mock function with given fields: subs
func (_m *MockSubServ) CreateSubcription(subs model.Subscription) error {
	ret := _m.Called(subs)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubcription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Subscription) error); ok {
		r0 = rf(subs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubServ_CreateSubcription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubcription'
type MockSubServ_CreateSubcription_Call struct {
	*mock.Call
}

// CreateSubcription is a helper method to define mock.On call
//   - subs model.Subscription
func (_e *MockSubServ_Expecter) CreateSubcription(subs interface{}) *MockSubServ_CreateSubcription_Call {
	return &MockSubServ_CreateSubcription_Call{Call: _e.mock.On("CreateSubcription", subs)}
}

func (_c *MockSubServ_CreateSubcription_Call) Run(run func(subs model.Subscription)) *MockSubServ_CreateSubcription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Subscription))
	})
	return _c
}

func (_c *MockSubServ_CreateSubcription_Call) Return(_a0 error) *MockSubServ_CreateSubcription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubServ_CreateSubcription_Call) RunAndReturn(run func(model.Subscription) error) *MockSubServ_CreateSubcription_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscription provides a mock function with given fields: userId, subsId
func (_m *MockSubServ) DeleteSubscription(userId uuid.UUID, subsId uuid.UUID) error {
	ret := _m.Called(userId, subsId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(userId, subsId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubServ_DeleteSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscription'
type MockSubServ_DeleteSubscription_Call struct {
	*mock.Call
}

// DeleteSubscription is a helper method to define mock.On call
//   - userId uuid.UUID
//   - subsId uuid.UUID
func (_e *MockSubServ_Expecter) DeleteSubscription(userId interface{}, subsId interface{}) *MockSubServ_DeleteSubscription_Call {
	return &MockSubServ_DeleteSubscription_Call{Call: _e.mock.On("DeleteSubscription", userId, subsId)}
}

func (_c *MockSubServ_DeleteSubscription_Call) Run(run func(userId uuid.UUID, subsId uuid.UUID)) *MockSubServ_DeleteSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubServ_DeleteSubscription_Call) Return(_a0 error) *MockSubServ_DeleteSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubServ_DeleteSubscription_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) error) *MockSubServ_DeleteSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionByUserID provides a mock function with given fields: userId
func (_m *MockSubServ) GetSubscriptionByUserID(userId uuid.UUID) ([]model.Subscription, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionByUserID")
	}

	var r0 []model.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]model.Subscription, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.Subscription); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubServ_GetSubscriptionByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionByUserID'
type MockSubServ_GetSubscriptionByUserID_Call struct {
	*mock.Call
}

// GetSubscriptionByUserID is a helper method to define mock.On call
//   - userId uuid.UUID
func (_e *MockSubServ_Expecter) GetSubscriptionByUserID(userId interface{}) *MockSubServ_GetSubscriptionByUserID_Call {
	return &MockSubServ_GetSubscriptionByUserID_Call{Call: _e.mock.On("GetSubscriptionByUserID", userId)}
}

func (_c *MockSubServ_GetSubscriptionByUserID_Call) Run(run func(userId uuid.UUID)) *MockSubServ_GetSubscriptionByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubServ_GetSubscriptionByUserID_Call) Return(_a0 []model.Subscription, _a1 error) *MockSubServ_GetSubscriptionByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubServ_GetSubscriptionByUserID_Call) RunAndReturn(run func(uuid.UUID) ([]model.Subscription, error)) *MockSubServ_GetSubscriptionByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubServ creates a new instance of MockSubServ. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubServ(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubServ {
	mock := &MockSubServ{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
