// Code generated by mockery v2.53.5. DO NOT EDIT.

package mockery

import (
	model "subscription/internal/adapters/model"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockSubscriptionRepo is an autogenerated mock type for the SubscriptionRepo type
type MockSubscriptionRepo struct {
	mock.Mock
}

type MockSubscriptionRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriptionRepo) EXPECT() *MockSubscriptionRepo_Expecter {
	return &MockSubscriptionRepo_Expecter{mock: &_m.Mock}
}

// CreateSubcription provides a mock function with given fields: u
func (_m *MockSubscriptionRepo) CreateSubcription(u model.Subscription) error {
	ret := _m.Called(u)

	if len(ret) == 0 {
		panic("no return value specified for CreateSubcription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Subscription) error); ok {
		r0 = rf(u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionRepo_CreateSubcription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSubcription'
type MockSubscriptionRepo_CreateSubcription_Call struct {
	*mock.Call
}

// CreateSubcription is a helper method to define mock.On call
//   - u model.Subscription
func (_e *MockSubscriptionRepo_Expecter) CreateSubcription(u interface{}) *MockSubscriptionRepo_CreateSubcription_Call {
	return &MockSubscriptionRepo_CreateSubcription_Call{Call: _e.mock.On("CreateSubcription", u)}
}

func (_c *MockSubscriptionRepo_CreateSubcription_Call) Run(run func(u model.Subscription)) *MockSubscriptionRepo_CreateSubcription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(model.Subscription))
	})
	return _c
}

func (_c *MockSubscriptionRepo_CreateSubcription_Call) Return(_a0 error) *MockSubscriptionRepo_CreateSubcription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionRepo_CreateSubcription_Call) RunAndReturn(run func(model.Subscription) error) *MockSubscriptionRepo_CreateSubcription_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSubscription provides a mock function with given fields: userId, subcriptionId
func (_m *MockSubscriptionRepo) DeleteSubscription(userId uuid.UUID, subcriptionId uuid.UUID) error {
	ret := _m.Called(userId, subcriptionId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscription")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(userId, subcriptionId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSubscriptionRepo_DeleteSubscription_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscription'
type MockSubscriptionRepo_DeleteSubscription_Call struct {
	*mock.Call
}

// DeleteSubscription is a helper method to define mock.On call
//   - userId uuid.UUID
//   - subcriptionId uuid.UUID
func (_e *MockSubscriptionRepo_Expecter) DeleteSubscription(userId interface{}, subcriptionId interface{}) *MockSubscriptionRepo_DeleteSubscription_Call {
	return &MockSubscriptionRepo_DeleteSubscription_Call{Call: _e.mock.On("DeleteSubscription", userId, subcriptionId)}
}

func (_c *MockSubscriptionRepo_DeleteSubscription_Call) Run(run func(userId uuid.UUID, subcriptionId uuid.UUID)) *MockSubscriptionRepo_DeleteSubscription_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionRepo_DeleteSubscription_Call) Return(_a0 error) *MockSubscriptionRepo_DeleteSubscription_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSubscriptionRepo_DeleteSubscription_Call) RunAndReturn(run func(uuid.UUID, uuid.UUID) error) *MockSubscriptionRepo_DeleteSubscription_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubscriptionsByUserID provides a mock function with given fields: userId
func (_m *MockSubscriptionRepo) GetSubscriptionsByUserID(userId uuid.UUID) ([]model.Subscription, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetSubscriptionsByUserID")
	}

	var r0 []model.Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) ([]model.Subscription, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) []model.Subscription); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSubscriptionRepo_GetSubscriptionsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubscriptionsByUserID'
type MockSubscriptionRepo_GetSubscriptionsByUserID_Call struct {
	*mock.Call
}

// GetSubscriptionsByUserID is a helper method to define mock.On call
//   - userId uuid.UUID
func (_e *MockSubscriptionRepo_Expecter) GetSubscriptionsByUserID(userId interface{}) *MockSubscriptionRepo_GetSubscriptionsByUserID_Call {
	return &MockSubscriptionRepo_GetSubscriptionsByUserID_Call{Call: _e.mock.On("GetSubscriptionsByUserID", userId)}
}

func (_c *MockSubscriptionRepo_GetSubscriptionsByUserID_Call) Run(run func(userId uuid.UUID)) *MockSubscriptionRepo_GetSubscriptionsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *MockSubscriptionRepo_GetSubscriptionsByUserID_Call) Return(_a0 []model.Subscription, _a1 error) *MockSubscriptionRepo_GetSubscriptionsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSubscriptionRepo_GetSubscriptionsByUserID_Call) RunAndReturn(run func(uuid.UUID) ([]model.Subscription, error)) *MockSubscriptionRepo_GetSubscriptionsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSubscriptionRepo creates a new instance of MockSubscriptionRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriptionRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriptionRepo {
	mock := &MockSubscriptionRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
